dist: trusty
script:
 - ${TRAVIS_BUILD_DIR}/cibuild
 # Run deploy_check only on Travis builds for the master branch
 - test "${TRAVIS_BRANCH-}" = "master" && ${TRAVIS_BUILD_DIR}/deploy_check

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: ${GH_ACCESS_TOKEN}  # Set in the Travis settings page for this repo
#   keep_history: true
#   target_branch: master
#   verbose: true
#   on:
#     branch: master

# Even if script fails (because of deploy_check), run cideploy on Travis
# builds on master branch IF deploy_check fails.
after_script:
 # This is a list of strings.
 # The ">" indicates a multi-line string using YAML's "folded-style".
 - >
   test "${TRAVIS_BRANCH-}" = "master" &&
   ! ${TRAVIS_BUILD_DIR}/deploy_check &&
   ${TRAVIS_BUILD_DIR}/cideploy

# Always test the master branch, even when there's no pull request
branches:
  only:
    - master
