#!/bin/bash
# Copies contents of file.txt into docs/file_copy.txt.

set -e

echo "CIDEPLOY"

# if [[ "${TRAVIS-}" && "${TRAVIS_BRANCH-}" = master && ! ./deploy_check ]]; then
#     ./deploy_starter_files
# fi

./deploy_starter_files

echo "CIDEPLOY DONE"
